#python main_gaussian.py --num_seller 1000 --num_dim 50 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --cluster
#python main_gaussian.py --num_seller 1000 --num_dim 500  --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --cluster

#python main_gaussian.py --num_seller 1000 --num_dim 100 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --cluster
#python main_gaussian.py --num_seller 1000 --num_dim 100 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator

#python main_gaussian.py --num_seller 1000 --num_dim 500 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --num_seller_subset 5 --seed 0
python main_gaussian.py --num_seller 1000 --num_dim 500 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --num_seller_subset 5 --seed 0
python main_gaussian.py --num_seller 1000 --num_dim 500 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --num_seller_subset 5 --seed 1
python main_gaussian.py --num_seller 1000 --num_dim 500 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --num_seller_subset 5 --seed 2
python main_gaussian.py --num_seller 1000 --num_dim 500 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --num_seller_subset 5 --seed 3
python main_gaussian.py --num_seller 1000 --num_dim 500 --num_val 100 --num_iters 100 --alpha 0.1 --baselines AME BetaShapley DataBanzhaf DataOob DataShapley DVRL InfluenceSubsample KNNShapley LavaEvaluator LeaveOneOut RandomEvaluator --num_seller_subset 5 --seed 4
